# Generated by Django 5.1.6 on 2025-02-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
